In [8]:
from joblib import dump,load
import numpy as np
model = load("Dragon.joblib")

In [9]:
feature = np.array([[-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.24141041, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034]])
model.predict(feature)

array([22.342])

In [14]:
import tkinter as tk

In [3]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
my_pipeline = Pipeline([
    ("Simple_Imputer", SimpleImputer(strategy="median")),
    #..many more can be add
    ("std_scalar",StandardScaler()),
])

In [6]:
CRIM = float(input("CRIM : "))
ZN = float(input("ZN : "))
INDUS = float(input("INDUS : "))
CHAS = float(input("CHAS : "))
NOX = float(input("NOX : "))
RM = float(input("RM : "))
AGE = float(input("AGE : "))
DIS = float(input("DIS : "))
RAD = float(input("RAD : "))
TAX = float(input("TAX: "))
PTRATIO = float(input("PTRATIO : "))
B = float(input("B : "))
LSTAT = float(input("LSTAT : "))

import numpy as np

given_data = np.array([[
    CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
]])

CRIM : 0.00632
ZN : 18
INDUS : 2.31
CHAS : 0
NOX : 0.538
RM : 6.575
AGE : 65.2
DIS : 4.09
RAD : 1
TAX: 296
PTRATIO : 15.3
B : 396.9
LSTAT : 4.98


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
model.predict(given_data)

array([23.624])

In [91]:
import tkinter.font as tkFont

# define function for price estimation

def price_estimator():
    if(CRIM_field.get()=="" and ZN_field.get()=="" and INDUS_field.get()=="" and CHAS_field.get()=="" and NOX_field.get()=="" and RM_field.get()==""and AGE_field.get()==""
       and DIS_field.get()==""and RAD_field.get()=="" and TAX_field.get()=="" and PTRTIO_field.get()=="" and B_field.get()=="" and LSTAT_field.get()==""):
        Total_Price_field.insert(0,"Please enter the values properly !")
    else:
        CRIM = float(CRIM_field.get())
        ZN = float(ZN_field.get())
        INDUS = float(INDUS_field.get())
        CHAS = float(CHAS_field.get())
        NOX = float(NOX_field.get())
        RM = float(RM_field.get())
        AGE = float(AGE_field.get())
        DIS = float(DIS_field.get())
        RAD = float(RAD_field.get())
        TAX = float(TAX_field.get())
        PTRTIO = float(PTRTIO_field.get())
        B = float(B_field.get())
        LSTAT = float(LSTAT_field.get())
        given_data = np.array([[
    CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT]])
        value = model.predict(given_data)
        price = value*1000
        price = str(int(price))+" Dollar"
        Total_Price_field.insert(0,price)

root = Tk() 
  
    # set the background colour of GUI window 
root.configure(background='light green') 
  
    # set the title of GUI window 
root.title("registration form") 
  
    # set the configuration of GUI window 
root.geometry("700x700")
fontStyle1 = tkFont.Font(family="Helvetica",weight="bold",underline="1" , size=25)
fontStyle2 = tkFont.Font(family="Lucida Grande", size=25)
heading = Label(root, text="Price Estimator of Real State", bg="red",font=fontStyle1) 

CRIM = Label(root, text="CRIM", bg="yellow")  
ZN = Label(root, text="ZN", bg="green")  
INDUS = Label(root, text="INDUS", bg="yellow")  
CHAS = Label(root, text="CHAS", bg="green")  
NOX = Label(root, text="NOX", bg="yellow") 
RM = Label(root, text="RM", bg="green") 
AGE = Label(root, text="AGE", bg="yellow")
DIS = Label(root, text="DIS", bg="green")
RAD = Label(root, text="RAD", bg="yellow")
TAX = Label(root, text="TAX", bg="green")
PTRTIO = Label(root, text="PTRTIO", bg="yellow")
B = Label(root, text="B", bg="green")
LSTAT = Label(root, text="LSTAT", bg="yellow")
Total_Price = Label(root, text="Total Price", bg="White",font=fontStyle2)


heading.grid(row=0, column=1,padx=10,pady=10) 
CRIM.grid(row=2, column=0,padx=5,pady=5,ipadx="15") 
ZN.grid(row=4, column=0,padx=5,pady=5,ipadx="20") 
INDUS.grid(row=6, column=0,padx=5,pady=5,ipadx="15") 
CHAS.grid(row=8, column=0,padx=5,pady=5,ipadx="15") 
NOX.grid(row=10, column=0,padx=5,pady=5,ipadx="18") 
RM.grid(row=12, column=0,padx=5,pady=5,ipadx="20") 
AGE.grid(row=14, column=0,padx=5,pady=5,ipadx="18")
DIS.grid(row=16, column=0,padx=5,pady=5,ipadx="18")
RAD.grid(row=18, column=0,padx=5,pady=5,ipadx="18")
TAX.grid(row=20, column=0,padx=5,pady=5,ipadx="18")
PTRTIO.grid(row=22, column=0,padx=5,pady=5,ipadx="10")
B.grid(row=24, column=0,padx=5,pady=5,ipadx="24")
LSTAT.grid(row=26, column=0,padx=5,pady=5,ipadx="12")
Total_Price.grid(row=30, column=0,padx=5,pady=5,ipadx="12")
 
    
    # create a text entry box 
    # for typing the information 
CRIM_field = Entry(root) 
ZN_field = Entry(root) 
INDUS_field = Entry(root) 
CHAS_field = Entry(root) 
NOX_field = Entry(root) 
RM_field = Entry(root) 
AGE_field = Entry(root)
DIS_field = Entry(root)
RAD_field = Entry(root)
TAX_field = Entry(root)
PTRTIO_field = Entry(root)
B_field = Entry(root)
LSTAT_field = Entry(root)
Total_Price_field = Entry(root)

CRIM_field.grid(row=2, column=1, ipadx="100") 
ZN_field.grid(row=4, column=1, ipadx="100") 
INDUS_field.grid(row=6, column=1, ipadx="100") 
CHAS_field.grid(row=8, column=1, ipadx="100") 
NOX_field.grid(row=10, column=1, ipadx="100") 
RM_field.grid(row=12, column=1, ipadx="100") 
AGE_field.grid(row=14, column=1, ipadx="100")
DIS_field.grid(row=16, column=1, ipadx="100")
RAD_field.grid(row=18, column=1, ipadx="100")
TAX_field.grid(row=20, column=1, ipadx="100")
PTRTIO_field.grid(row=22, column=1, ipadx="100")
B_field.grid(row=24, column=1, ipadx="100")
LSTAT_field.grid(row=26, column=1, ipadx="100")
submit = Button(root, text="Submit", fg="Black", bg="Red",padx="5",pady="5", command=price_estimator) 
submit.grid(row=28, column=1) 
Total_Price_field.grid(row=30, column=1,padx="5",pady="5",ipadx="50",ipady="20")


root.mainloop()